variables:
  project: eu
  author: "eu de novo"

templates:
  primeira:
    pattern: "{project} teste aqui {author}"
    prefix: "antes do texto"
    suffix: "depois do texto"
  segunda:
    pattern: "{scope} {message}"
    prefix: ""
    suffix: ""
